export default [
  { id: 1, title: "AFANATEBS", artist: "IceKvara", src: "music/IceKvara - AFANATEBS.mp3" },
  { id: 2, title: "Arround", artist: "IceKvara", src: "music/Icekvara - Arround.mp3" },
  { id: 3, title: "BAD LINES", artist: "IceKvara", src: "music/Icekvara - BAD LINES.mp3" },
  { id: 4, title: "DRAWING", artist: "IceKvara", src: "music/Icekvara - DRAWING.mp3" },
  { id: 5, title: "FOREVER (mixtape final track)", artist: "IceKvara", src: "music/Icekvara - FOREVER (mixtape final track).mp3" },
  { id: 6, title: "GAIGON", artist: "IceKvara", src: "music/Icekvara - GAIGON.mp3" },
  { id: 7, title: "IDEALI", artist: "IceKvara", src: "music/Icekvara - IDEALI.mp3" },
  { id: 8, title: "INSTA", artist: "IceKvara", src: "music/Icekvara - INSTA.mp3" },
  { id: 9, title: "issue", artist: "IceKvara ft. flockaa99", src: "music/Icekvara - issue (Ft.flockaa99).mp3" },
  { id: 10, title: "Lisa", artist: "IceKvara", src: "music/Icekvara - Lisa.mp3" },
  { id: 11, title: "MALAMO", artist: "IceKvara", src: "music/Icekvara - MALAMO.mp3" },
  { id: 12, title: "manipulation", artist: "IceKvara ft. flockaa99", src: "music/Icekvara - manipulation (Ft.flockaa99).mp3" },
  { id: 13, title: "ME", artist: "IceKvara", src: "music/Icekvara - ME.mp3" },
  { id: 14, title: "Message", artist: "IceKvara ft. flcoka99", src: "music/Icekvara - Message (Ft.flcoka99).mp3" },
  { id: 15, title: "MIND", artist: "IceKvara", src: "music/Icekvara - MIND.mp3" },
  { id: 16, title: "NoNe", artist: "IceKvara", src: "music/Icekvara - NoNe.mp3" },
  { id: 17, title: "Noway A", artist: "IceKvara", src: "music/Icekvara - Noway A.mp3" },
  { id: 18, title: "Noway B", artist: "IceKvara", src: "music/Icekvara - Noway B.mp3" },
  { id: 19, title: "OUTRO", artist: "IceKvara", src: "music/Icekvara - OUTRO.mp3" },
  { id: 20, title: "PlayaFa", artist: "IceKvara", src: "music/Icekvara - PlayaFa.mp3" },
  { id: 21, title: "Real Me", artist: "IceKvara", src: "music/Icekvara - Real Me.mp3" },
  { id: 22, title: "Tell me what love is", artist: "IceKvara", src: "music/Icekvara - Tell me what love is_.mp3" },
  { id: 23, title: "Will", artist: "IceKvara ft. Miqael", src: "music/IceKvara - Will (Ft.Miqael).mp3" },
  { id: 24, title: "ZARA", artist: "IceKvara", src: "music/Icekvara - ZARA.mp3" },
  { id: 25, title: "რატომ მე", artist: "IceKvara ft. Flockaa", src: "music/Icekvara - რატომ მე_ (Ft.Flockaa).mp3" },
  { id: 26, title: "Two Saint Angels", artist: "IceKvara X Flockaa99", src: "music/IceKvara X Flockaa99 - Two Saint Angels.mp3" },
  { id: 27, title: "ANTISOCIAL", artist: "Kvara", src: "music/Kvara - ANTISOCIAL.mp3" },
  { id: 28, title: "Away", artist: "Kvara", src: "music/Kvara - Away.mp3" },
  { id: 29, title: "FAILED MISSION", artist: "Kvara", src: "music/Kvara - FAILED MISSION.mp3" },
  { id: 30, title: "Falling Stars", artist: "Kvara", src: "music/Kvara - Falling Stars.mp3" },
  { id: 31, title: "Glock19 (REMAKE)", artist: "Kvara", src: "music/Kvara - Glock19 [REMAKE].mp3" },
  { id: 32, title: "hielo derretido", artist: "Kvara", src: "music/Kvara - hielo derretido.mp3" },
  { id: 33, title: "Hologram", artist: "Kvara", src: "music/Kvara - Hologram.mp3" },
  { id: 34, title: "house rules (HBD Bro)", artist: "Kvara", src: "music/Kvara - house rules (HBD Bro) - Copy (2).mp3" },
  { id: 35, title: "ICEDD", artist: "Kvara", src: "music/Kvara - ICEDD.mp3" },
  { id: 36, title: "kisses for me", artist: "Kvara", src: "music/Kvara - kisses for me.mp3" },
  { id: 37, title: "MIST1KA", artist: "Kvara ft. flockaa", src: "music/Kvara - MIST1KA (ft.flockaa).mp3" },
  { id: 38, title: "NIGHT SHOT", artist: "Kvara ft. Nyvoxx", src: "music/Kvara - NIGHT SHOT (ft.Nyvoxx).mp3" },
  { id: 39, title: "RAGAMAN", artist: "Kvara ft. flockaa", src: "music/Kvara - RAGAMAN (ft.flockaa).mp3" },
  { id: 40, title: "SANTELI", artist: "Kvara", src: "music/Kvara - SANTELI.mp3" },
  { id: 41, title: "Shooting Ice", artist: "Kvara", src: "music/Kvara - Shooting Ice.mp3" },
  { id: 42, title: "SINATLE", artist: "Kvara", src: "music/Kvara - SINATLE.mp3" },
  { id: 43, title: "SNAKE HES", artist: "Kvara ft. flockaaa", src: "music/Kvara - SNAKE HES (ft.flockaaa).mp3" },
  { id: 44, title: "STILL LOVE", artist: "Kvara", src: "music/Kvara - STILL LOVE_.mp3" },
  { id: 45, title: "STORM", artist: "Kvara ft. flockaa99", src: "music/Kvara - STORM (ft.flockaa99).mp3" },
  { id: 46, title: "Super Cars", artist: "Kvara ft. Unknown", src: "music/Kvara - Super Cars (Ft.Unknown).mp3" },
  { id: 47, title: "True", artist: "Kvara", src: "music/Kvara - True_.mp3" },
  { id: 48, title: "Under", artist: "Kvara", src: "music/Kvara - Under.mp3" },
  { id: 49, title: "V3TERANI", artist: "Kvara ft. Flockaa", src: "music/Kvara - V3TERANI (Ft.Flockaa).mp3" },
  { id: 50, title: "BLABLASETTINGS", artist: "Kvara", src: "music/BLABLASETTINGS.m4a" },
  { id: 51, title: "Flying", artist: "Kvara", src: "music/Flying.m4a" },
  { id: 52, title: "Garfosfeat", artist: "Kvara", src: "music/Garfosfeat.m4a" },
  { id: 53, title: "HappyLoss", artist: "Kvara", src: "music/HappyLoss.m4a" }
];